[package]
name = "users"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { workspace = true }
actix-web = { workspace = true }
utils = { workspace = true }
diesel = { workspace = true }
chrono = { workspace = true }
jsonwebtoken = { workspace = true }