[package]
name = "backend"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = { workspace = true }

utils = {workspace = true }
anyhow = { workspace = true }
env_logger = { workspace = true }